version: '3.8'
services:
    postgres:
        image: postgres:latest
        container_name: harvtech-postgres
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:${DB_DOCKER_PORT}"
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
